version: 2.1
parameters:
  python-version:
    default: '3.9'
    type: enum
    enum: ['3.6', '3.7', '3.8', '3.9']

jobs:
  adas-python-tests:
    docker:
      - image: circleci/python:<<pipeline.parameters.python-version>>
    steps:
      - checkout
      - run:
          name: pyadas installation
          command:
            python --version
            pip install --upgrade pip
            pip install -r requirements-dev.txt
            pip install . --verbose

      - run:
          name: unittests
          command: |
            pytest tests/unit_test/ -p "*.py" -v

  adas-python-coverage:
    docker:
      - image: circleci/python:3.9.4
    steps:
      - checkout
      - run:
          name: test and collect coverage
          command: |
            pip install -r requirements-dev.txt
            pip install .
            pytest --cov=adas --cov-report=xml tests/unit_test/**/*.py

      - run:
          name: upload coverage
          command: |
            bash <(curl -s https://codecov.io/bash)


  adas-cxx-compilation:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - run:
          name: Install cxx enviroment
          command: 
            sudo apt-get -y update && sudo apt-get -y install cmake libboost-program-options-dev libboost-test-dev
      - run:
          name: Build test and run unit-tests
          command: |
            mkdir -p build && cmake -B build -DCMAKE_BUILD_TYPE=Debug --log-level=debug
            cd build && make && make test

            
workflows:
  version: 2
  adas-build:
    jobs:
      - adas-python-tests
      - adas-python-coverage:
          requires:
            - adas-python-tests
      - adas-cxx-compilation
